# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDecision(TypedDict):
    # the origin of the decision : cscli, crowdsec
    origin: str

    # the type of decision, might be 'ban', 'captcha' or something custom. Ignored when watcher (cscli/crowdsec) is pushing to APIL.
    type: str

    # the scope of decision : does it apply to an IP, a range, a username, etc
    scope: str

    # the value of the decision scope : an IP, a range, a username, etc
    value: str

    # the duration of the decisions
    duration: str

    scenario: str

class OptionalDecision(TypedDict, total=False):
    # (only relevant for GET ops) the unique id
    id: int

    # only relevant for LAPI->CAPI, ignored for cscli->LAPI and crowdsec->LAPI
    uuid: str

    # the date until the decisions must be active
    until: str

    # true if the decision result from a scenario in simulation mode
    simulated: bool

class Decision(RequiredDecision, OptionalDecision):
    pass
