# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMetricsAgentInfo(TypedDict):
    pass

class OptionalMetricsAgentInfo(TypedDict, total=False):
    # software version
    version: str

    # name of the component
    name: str

    # last agent update date
    last_update: str

    # last agent push date
    last_push: str

class MetricsAgentInfo(RequiredMetricsAgentInfo, OptionalMetricsAgentInfo):
    pass
