# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMetricsBouncerInfo(TypedDict):
    pass

class OptionalMetricsBouncerInfo(TypedDict, total=False):
    # software version
    version: str

    # name of the component
    custom_name: str

    # bouncer type (firewall, php ...)
    name: str

    # last bouncer pull date
    last_pull: str

class MetricsBouncerInfo(RequiredMetricsBouncerInfo, OptionalMetricsBouncerInfo):
    pass
