# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSource(TypedDict):
    # the scope of a source : ip,range,username,etc
    scope: str

    # the value of a source : the ip, the range, the username,etc
    value: str

class OptionalSource(TypedDict, total=False):
    # provided as a convenience when the source is an IP
    ip: str

    # provided as a convenience when the source is an IP
    range: str

    # provided as a convenience when the source is an IP
    as_number: str

    # provided as a convenience when the source is an IP
    as_name: str

    cn: str

    latitude: typing.Union[int, float]

    longitude: typing.Union[int, float]

class Source(RequiredSource, OptionalSource):
    pass
