# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWatcherAuthResponse(TypedDict):
    pass

class OptionalWatcherAuthResponse(TypedDict, total=False):
    code: int

    expire: str

    token: str

class WatcherAuthResponse(RequiredWatcherAuthResponse, OptionalWatcherAuthResponse):
    pass
