# coding: utf-8

# flake8: noqa

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from crowd_sec_python_sdk.api_client import ApiClient

# import Configuration
from crowd_sec_python_sdk.configuration import Configuration

# import exceptions
from crowd_sec_python_sdk.exceptions import OpenApiException
from crowd_sec_python_sdk.exceptions import ApiAttributeError
from crowd_sec_python_sdk.exceptions import ApiTypeError
from crowd_sec_python_sdk.exceptions import ApiValueError
from crowd_sec_python_sdk.exceptions import ApiKeyError
from crowd_sec_python_sdk.exceptions import ApiException

from crowd_sec_python_sdk.client import CrowdSec
