# coding: utf-8
"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from crowd_sec_python_sdk.client_custom import ClientCustom
from crowd_sec_python_sdk.configuration import Configuration
from crowd_sec_python_sdk.api_client import ApiClient
from crowd_sec_python_sdk.type_util import copy_signature
from crowd_sec_python_sdk.apis.tags.bouncers_api import BouncersApi
from crowd_sec_python_sdk.apis.tags.watchers_api import WatchersApi



class CrowdSec(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.bouncers: BouncersApi = BouncersApi(api_client)
        self.watchers: WatchersApi = WatchersApi(api_client)
