# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from crowd_sec_python_sdk import CrowdSec

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        crowdsec = CrowdSec(
        
                        api_key_authorizer = 'YOUR_API_KEY',
        
                        jwt_authorizer = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(crowdsec)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
