# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from crowd_sec_python_sdk.paths.decisions_stream.get import GetDecisionsStream
from crowd_sec_python_sdk.paths.decisions_stream.head import GetDecisionsStream0
from crowd_sec_python_sdk.paths.decisions.get import GetInformation
from crowd_sec_python_sdk.paths.decisions.head import GetInformation0
from crowd_sec_python_sdk.apis.tags.bouncers_api_raw import BouncersApiRaw


class BouncersApi(
    GetDecisionsStream,
    GetDecisionsStream0,
    GetInformation,
    GetInformation0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BouncersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BouncersApiRaw(api_client)
