# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from crowd_sec_python_sdk.paths.watchers_login.post import AuthenticateSessionRaw
from crowd_sec_python_sdk.paths.alerts.post import CreateAlertsRaw
from crowd_sec_python_sdk.paths.alerts_alert_id.delete import DeleteAlertByIdRaw
from crowd_sec_python_sdk.paths.alerts_alert_id.get import GetAlertByIdRaw
from crowd_sec_python_sdk.paths.alerts_alert_id.head import GetAlertById0Raw
from crowd_sec_python_sdk.paths.alerts.get import ListAlertsRaw
from crowd_sec_python_sdk.paths.watchers.post import RegisterWatcherRaw
from crowd_sec_python_sdk.paths.alerts.delete import RemoveAlertsRaw
from crowd_sec_python_sdk.paths.decisions_decision_id.delete import RemoveDecisionByIdRaw
from crowd_sec_python_sdk.paths.decisions.delete import RemoveDecisionsRaw
from crowd_sec_python_sdk.paths.alerts.head import SearchAlertsRaw


class WatchersApiRaw(
    AuthenticateSessionRaw,
    CreateAlertsRaw,
    DeleteAlertByIdRaw,
    GetAlertByIdRaw,
    GetAlertById0Raw,
    ListAlertsRaw,
    RegisterWatcherRaw,
    RemoveAlertsRaw,
    RemoveDecisionByIdRaw,
    RemoveDecisionsRaw,
    SearchAlertsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
