# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from crowd_sec_python_sdk.paths.watchers_login.post import AuthenticateSession
from crowd_sec_python_sdk.paths.alerts.post import CreateAlerts
from crowd_sec_python_sdk.paths.alerts_alert_id.delete import DeleteAlertById
from crowd_sec_python_sdk.paths.alerts_alert_id.get import GetAlertById
from crowd_sec_python_sdk.paths.alerts_alert_id.head import GetAlertById0
from crowd_sec_python_sdk.paths.alerts.get import ListAlerts
from crowd_sec_python_sdk.paths.watchers.post import RegisterWatcher
from crowd_sec_python_sdk.paths.alerts.delete import RemoveAlerts
from crowd_sec_python_sdk.paths.decisions_decision_id.delete import RemoveDecisionById
from crowd_sec_python_sdk.paths.decisions.delete import RemoveDecisions
from crowd_sec_python_sdk.paths.alerts.head import SearchAlerts
from crowd_sec_python_sdk.apis.tags.watchers_api_raw import WatchersApiRaw


class WatchersApi(
    AuthenticateSession,
    CreateAlerts,
    DeleteAlertById,
    GetAlertById,
    GetAlertById0,
    ListAlerts,
    RegisterWatcher,
    RemoveAlerts,
    RemoveDecisionById,
    RemoveDecisions,
    SearchAlerts,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WatchersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WatchersApiRaw(api_client)
