# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import crowd_sec_python_sdk
from crowd_sec_python_sdk.paths.alerts import post
from crowd_sec_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestAlerts(ApiTestMixin, unittest.TestCase):
    """
    Alerts unit test stubs
        pushAlerts
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
