# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

import unittest

import crowd_sec_python_sdk
from crowd_sec_python_sdk.model.watcher_registration_request import WatcherRegistrationRequest
from crowd_sec_python_sdk import configuration


class TestWatcherRegistrationRequest(unittest.TestCase):
    """WatcherRegistrationRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
