# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

import unittest

import crowd_sec_python_sdk
from crowd_sec_python_sdk.model.get_decisions_response import GetDecisionsResponse
from crowd_sec_python_sdk import configuration


class TestGetDecisionsResponse(unittest.TestCase):
    """GetDecisionsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
