# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from crowd_sec_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from crowd_sec_python_sdk.api_response import AsyncGeneratorResponse
from crowd_sec_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_sec_python_sdk import schemas  # noqa: F401

from crowd_sec_python_sdk.model.get_decisions_response import GetDecisionsResponse as GetDecisionsResponseSchema
from crowd_sec_python_sdk.model.error_response import ErrorResponse as ErrorResponseSchema

from crowd_sec_python_sdk.type.get_decisions_response import GetDecisionsResponse
from crowd_sec_python_sdk.type.error_response import ErrorResponse

from ...api_client import Dictionary
from crowd_sec_python_sdk.pydantic.get_decisions_response import GetDecisionsResponse as GetDecisionsResponsePydantic
from crowd_sec_python_sdk.pydantic.error_response import ErrorResponse as ErrorResponsePydantic

from . import path

# Query params
ScopeSchema = schemas.StrSchema
ValueSchema = schemas.StrSchema
TypeSchema = schemas.StrSchema
IpSchema = schemas.StrSchema
RangeSchema = schemas.StrSchema
ContainsSchema = schemas.BoolSchema
OriginsSchema = schemas.StrSchema
ScenariosContainingSchema = schemas.StrSchema
ScenariosNotContainingSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'scope': typing.Union[ScopeSchema, str, ],
        'value': typing.Union[ValueSchema, str, ],
        'type': typing.Union[TypeSchema, str, ],
        'ip': typing.Union[IpSchema, str, ],
        'range': typing.Union[RangeSchema, str, ],
        'contains': typing.Union[ContainsSchema, bool, ],
        'origins': typing.Union[OriginsSchema, str, ],
        'scenarios_containing': typing.Union[ScenariosContainingSchema, str, ],
        'scenarios_not_containing': typing.Union[ScenariosNotContainingSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_scope = api_client.QueryParameter(
    name="scope",
    style=api_client.ParameterStyle.FORM,
    schema=ScopeSchema,
    explode=True,
)
request_query_value = api_client.QueryParameter(
    name="value",
    style=api_client.ParameterStyle.FORM,
    schema=ValueSchema,
    explode=True,
)
request_query_type = api_client.QueryParameter(
    name="type",
    style=api_client.ParameterStyle.FORM,
    schema=TypeSchema,
    explode=True,
)
request_query_ip = api_client.QueryParameter(
    name="ip",
    style=api_client.ParameterStyle.FORM,
    schema=IpSchema,
    explode=True,
)
request_query_range = api_client.QueryParameter(
    name="range",
    style=api_client.ParameterStyle.FORM,
    schema=RangeSchema,
    explode=True,
)
request_query_contains = api_client.QueryParameter(
    name="contains",
    style=api_client.ParameterStyle.FORM,
    schema=ContainsSchema,
    explode=True,
)
request_query_origins = api_client.QueryParameter(
    name="origins",
    style=api_client.ParameterStyle.FORM,
    schema=OriginsSchema,
    explode=True,
)
request_query_scenarios_containing = api_client.QueryParameter(
    name="scenarios_containing",
    style=api_client.ParameterStyle.FORM,
    schema=ScenariosContainingSchema,
    explode=True,
)
request_query_scenarios_not_containing = api_client.QueryParameter(
    name="scenarios_not_containing",
    style=api_client.ParameterStyle.FORM,
    schema=ScenariosNotContainingSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = GetDecisionsResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: GetDecisionsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: GetDecisionsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ErrorResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ErrorResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ErrorResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_information_mapped_args(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if scope is not None:
            _query_params["scope"] = scope
        if value is not None:
            _query_params["value"] = value
        if type is not None:
            _query_params["type"] = type
        if ip is not None:
            _query_params["ip"] = ip
        if range is not None:
            _query_params["range"] = range
        if contains is not None:
            _query_params["contains"] = contains
        if origins is not None:
            _query_params["origins"] = origins
        if scenarios_containing is not None:
            _query_params["scenarios_containing"] = scenarios_containing
        if scenarios_not_containing is not None:
            _query_params["scenarios_not_containing"] = scenarios_not_containing
        args.query = _query_params
        return args

    async def _aget_information_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        getDecisions
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_scope,
            request_query_value,
            request_query_type,
            request_query_ip,
            request_query_range,
            request_query_contains,
            request_query_origins,
            request_query_scenarios_containing,
            request_query_scenarios_not_containing,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/decisions',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_information_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        getDecisions
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_scope,
            request_query_value,
            request_query_type,
            request_query_ip,
            request_query_range,
            request_query_contains,
            request_query_origins,
            request_query_scenarios_containing,
            request_query_scenarios_not_containing,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/decisions',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetInformationRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_information(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_information_mapped_args(
            scope=scope,
            value=value,
            type=type,
            ip=ip,
            range=range,
            contains=contains,
            origins=origins,
            scenarios_containing=scenarios_containing,
            scenarios_not_containing=scenarios_not_containing,
        )
        return await self._aget_information_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_information(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_information_mapped_args(
            scope=scope,
            value=value,
            type=type,
            ip=ip,
            range=range,
            contains=contains,
            origins=origins,
            scenarios_containing=scenarios_containing,
            scenarios_not_containing=scenarios_not_containing,
        )
        return self._get_information_oapg(
            query_params=args.query,
        )

class GetInformation(BaseApi):

    async def aget_information(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> GetDecisionsResponsePydantic:
        raw_response = await self.raw.aget_information(
            scope=scope,
            value=value,
            type=type,
            ip=ip,
            range=range,
            contains=contains,
            origins=origins,
            scenarios_containing=scenarios_containing,
            scenarios_not_containing=scenarios_not_containing,
            **kwargs,
        )
        if validate:
            return RootModel[GetDecisionsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(GetDecisionsResponsePydantic, raw_response.body)
    
    
    def get_information(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
        validate: bool = False,
    ) -> GetDecisionsResponsePydantic:
        raw_response = self.raw.get_information(
            scope=scope,
            value=value,
            type=type,
            ip=ip,
            range=range,
            contains=contains,
            origins=origins,
            scenarios_containing=scenarios_containing,
            scenarios_not_containing=scenarios_not_containing,
        )
        if validate:
            return RootModel[GetDecisionsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(GetDecisionsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_information_mapped_args(
            scope=scope,
            value=value,
            type=type,
            ip=ip,
            range=range,
            contains=contains,
            origins=origins,
            scenarios_containing=scenarios_containing,
            scenarios_not_containing=scenarios_not_containing,
        )
        return await self._aget_information_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        scope: typing.Optional[str] = None,
        value: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        ip: typing.Optional[str] = None,
        range: typing.Optional[str] = None,
        contains: typing.Optional[bool] = None,
        origins: typing.Optional[str] = None,
        scenarios_containing: typing.Optional[str] = None,
        scenarios_not_containing: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_information_mapped_args(
            scope=scope,
            value=value,
            type=type,
            ip=ip,
            range=range,
            contains=contains,
            origins=origins,
            scenarios_containing=scenarios_containing,
            scenarios_not_containing=scenarios_not_containing,
        )
        return self._get_information_oapg(
            query_params=args.query,
        )

