# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from crowd_sec_python_sdk.pydantic.get_decisions_response import GetDecisionsResponse

class DecisionsStreamResponse(BaseModel):
    new: typing.Optional[GetDecisionsResponse] = Field(None, alias='new')

    deleted: typing.Optional[GetDecisionsResponse] = Field(None, alias='deleted')
    class Config:
        arbitrary_types_allowed = True
