# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ErrorResponse(BaseModel):
    # Error message
    message: str = Field(alias='message')

    # more detail on individual errors
    errors: typing.Optional[str] = Field(None, alias='errors')
    class Config:
        arbitrary_types_allowed = True
