# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class MetricsBouncerInfo(BaseModel):
    # software version
    version: typing.Optional[str] = Field(None, alias='version')

    # name of the component
    custom_name: typing.Optional[str] = Field(None, alias='custom_name')

    # bouncer type (firewall, php ...)
    name: typing.Optional[str] = Field(None, alias='name')

    # last bouncer pull date
    last_pull: typing.Optional[str] = Field(None, alias='last_pull')
    class Config:
        arbitrary_types_allowed = True
