# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from crowd_sec_python_sdk.pydantic.metrics_agent_info import MetricsAgentInfo
from crowd_sec_python_sdk.pydantic.metrics_bouncer_info import MetricsBouncerInfo

class Metrics(BaseModel):
    # the local version of crowdsec/apil
    apil_version: str = Field(alias='apil_version')

    bouncers: typing.List[MetricsBouncerInfo] = Field(alias='bouncers')

    machines: typing.List[MetricsAgentInfo] = Field(alias='machines')
    class Config:
        arbitrary_types_allowed = True
