# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class MetricsAgentInfo(BaseModel):
    # software version
    version: typing.Optional[str] = Field(None, alias='version')

    # name of the component
    name: typing.Optional[str] = Field(None, alias='name')

    # last agent update date
    last_update: typing.Optional[str] = Field(None, alias='last_update')

    # last agent push date
    last_push: typing.Optional[str] = Field(None, alias='last_push')
    class Config:
        arbitrary_types_allowed = True
