# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Source(BaseModel):
    # the scope of a source : ip,range,username,etc
    scope: str = Field(alias='scope')

    # the value of a source : the ip, the range, the username,etc
    value: str = Field(alias='value')

    # provided as a convenience when the source is an IP
    ip: typing.Optional[str] = Field(None, alias='ip')

    # provided as a convenience when the source is an IP
    range: typing.Optional[str] = Field(None, alias='range')

    # provided as a convenience when the source is an IP
    as_number: typing.Optional[str] = Field(None, alias='as_number')

    # provided as a convenience when the source is an IP
    as_name: typing.Optional[str] = Field(None, alias='as_name')

    cn: typing.Optional[str] = Field(None, alias='cn')

    latitude: typing.Optional[typing.Union[int, float]] = Field(None, alias='latitude')

    longitude: typing.Optional[typing.Union[int, float]] = Field(None, alias='longitude')
    class Config:
        arbitrary_types_allowed = True
