# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from crowd_sec_python_sdk.pydantic.watcher_auth_request_scenarios import WatcherAuthRequestScenarios

class WatcherAuthRequest(BaseModel):
    machine_id: str = Field(alias='machine_id')

    password: str = Field(alias='password')

    scenarios: typing.Optional[WatcherAuthRequestScenarios] = Field(None, alias='scenarios')
    class Config:
        arbitrary_types_allowed = True
