# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_sec_python_sdk import schemas  # noqa: F401


class Meta(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    the Meta data of the Alert itself
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['MetaItem']:
            return MetaItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['MetaItem'], typing.List['MetaItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'Meta':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'MetaItem':
        return super().__getitem__(i)

from crowd_sec_python_sdk.model.meta_item import MetaItem
