# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_sec_python_sdk import schemas  # noqa: F401


class Metrics(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "bouncers",
            "apil_version",
            "machines",
        }
        
        class properties:
            apil_version = schemas.StrSchema
            
            
            class bouncers(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['MetricsBouncerInfo']:
                        return MetricsBouncerInfo
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['MetricsBouncerInfo'], typing.List['MetricsBouncerInfo']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'bouncers':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'MetricsBouncerInfo':
                    return super().__getitem__(i)
            
            
            class machines(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['MetricsAgentInfo']:
                        return MetricsAgentInfo
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['MetricsAgentInfo'], typing.List['MetricsAgentInfo']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'machines':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'MetricsAgentInfo':
                    return super().__getitem__(i)
            __annotations__ = {
                "apil_version": apil_version,
                "bouncers": bouncers,
                "machines": machines,
            }
    
    bouncers: MetaOapg.properties.bouncers
    apil_version: MetaOapg.properties.apil_version
    machines: MetaOapg.properties.machines
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["apil_version"]) -> MetaOapg.properties.apil_version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bouncers"]) -> MetaOapg.properties.bouncers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["machines"]) -> MetaOapg.properties.machines: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["apil_version", "bouncers", "machines", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["apil_version"]) -> MetaOapg.properties.apil_version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bouncers"]) -> MetaOapg.properties.bouncers: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["machines"]) -> MetaOapg.properties.machines: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["apil_version", "bouncers", "machines", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        bouncers: typing.Union[MetaOapg.properties.bouncers, list, tuple, ],
        apil_version: typing.Union[MetaOapg.properties.apil_version, str, ],
        machines: typing.Union[MetaOapg.properties.machines, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Metrics':
        return super().__new__(
            cls,
            *args,
            bouncers=bouncers,
            apil_version=apil_version,
            machines=machines,
            _configuration=_configuration,
            **kwargs,
        )

from crowd_sec_python_sdk.model.metrics_agent_info import MetricsAgentInfo
from crowd_sec_python_sdk.model.metrics_bouncer_info import MetricsBouncerInfo
