# coding: utf-8

"""
    Swagger CrowdSec

    CrowdSec local API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@crowdsec.net
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import crowd_sec_python_sdk
from crowd_sec_python_sdk.paths.decisions_decision_id import delete
from crowd_sec_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestDecisionsDecisionId(ApiTestMixin, unittest.TestCase):
    """
    DecisionsDecisionId unit test stubs
        DeleteDecision
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
